// <auto-generated />
using System;
using LoanCar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanCar.Data.Migrations
{
    [DbContext(typeof(CrudApiDbContext))]
    [Migration("20201208174035_InitializationDb")]
    partial class InitializationDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanCar.Data.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(135)")
                        .HasMaxLength(135);

                    b.Property<string>("ApplicantCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ApplicantDateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<short>("ApplicantHowLongMonth")
                        .HasColumnType("smallint");

                    b.Property<short>("ApplicantHowLongYear")
                        .HasColumnType("smallint");

                    b.Property<string>("ApplicantLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ApplicantMiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("ApplicantPhone")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicantPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("ApplicantProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<long>("ApplicantSIN")
                        .HasColumnType("bigint");

                    b.Property<long>("CpApplicantPhone")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DriverLicence")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ExpDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MarketValue")
                        .HasColumnType("bigint");

                    b.Property<long>("Mortgage")
                        .HasColumnType("bigint");

                    b.Property<long>("MortgageBalance")
                        .HasColumnType("bigint");

                    b.Property<string>("MortgageHolder")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("NatureBusiness")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("OwnStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("PresentEmployerAddress")
                        .HasColumnType("nvarchar(135)")
                        .HasMaxLength(135);

                    b.Property<short>("PresentEmployerHowLongMonth")
                        .HasColumnType("smallint");

                    b.Property<short>("PresentEmployerHowLongYear")
                        .HasColumnType("smallint");

                    b.Property<long>("PresentEmployerMonthlyIncome")
                        .HasColumnType("bigint");

                    b.Property<string>("PresentEmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PresentEmployerOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<long>("PresentEmployerPhone")
                        .HasColumnType("bigint");

                    b.Property<string>("PresentEmployerTwoIncome")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("PreviousApplicantAddress")
                        .HasColumnType("nvarchar(135)")
                        .HasMaxLength(135);

                    b.Property<string>("PreviousApplicantCity")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<short>("PreviousApplicantHowLongMonth")
                        .HasColumnType("smallint");

                    b.Property<short>("PreviousApplicantHowLongYear")
                        .HasColumnType("smallint");

                    b.Property<string>("PreviousApplicantPostalCode")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("PreviousApplicantProvince")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("SpouseDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseFirstName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SpouseLastName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SpouseMiddleName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("SpouseSIN")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Loan","fac");
                });
#pragma warning restore 612, 618
        }
    }
}
